name: DokGreetingsBot

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            '<h1>It's great having you contribute to this project</h1> Welcome to Dok community :nerd_face:' |
            '<br>The maintainers will get back to you soon for discussion over the issue!'
        
        pr-message:  |
            '<h1>It's great having you contribute to this project</h1> Welcome to Dok community :nerd_face:' |
            '<h3>Now, Relax 😉 -> Grab a drink ☕ -> And wait for the maintainers views on your contribution. Meanwhile you can discuss on other issues and solve them 😀</h3>'
