name: issue-automation

on: [issues]
  
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
        - name: Labeler
          uses: actions/labeler@v4.0.0
          with:
          keywords: '["DOCS"]'
          add-labels: "documentation"
          ignore-if-labeled: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"


